service: socialbackendnodejs
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 2048
  timeout: 15

functions:
  hello:
    handler: handler.serverAPI
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      DB_URL: mongodb+srv://DBAdmin:social2022@cluster0.kh5nw.mongodb.net/socialApp
      SECRET_KEY: nfdsfn43346654ncsdfn53463453
